src/highland_fm_roster/highland_fm_roster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('roster.urls')),
    path('admin/', admin.site.urls),
]

src/highland_fm_roster/roster/urls.py
"""Urls patterns for roster app"""
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'roster'

urlpatterns = [
    path('', TemplateView.as_view(template_name='roster/home.html'), name='home'),
    path('staffs/', views.StaffListView.as_view(), name='staffsList'),
    path('staffs/new/', views.CreateStaffView.as_view(), name='newStaff'),
    path('staffs/<int:id>/', views.StaffActionsView.as_view(), name='staffActions')
]

src/highland_fm_roster/roster/models.py
"""Models for the roster app."""
from django.core.validators import MinValueValidator
from django.db import models


class Staff(models.Model):
    """Represents a staff of highland FM
    Attributes:
    - firstName: First name of the staff.
    - middleName: Middle name of the staff.
    - lastName: Last name or surname of the staff.
    - createdAt: Time of creation.
    - updatedAt: Time of last update.
    """

    firstName = models.CharField(max_length=50, blank=False, null=False, help_text="First name")
    middleName = models.CharField(max_length=50, blank=True, null=False, help_text="Middle name")
    lastName = models.CharField(max_length=50, blank=False, null=False, help_text="Last name (Surname)")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["firstName", "middleName", "lastName"]

    def __str__(self) -> str:
        """Returns a string representation of staff."""
        if self.middleName:
            return f"{self.firstName} {self.middleName} {self.lastName}"
        return f"{self.firstName} {self.lastName}"


class Roster(models.Model):
    """Represents a monthly roster.
    Attributes:
    - date: Represent the month in which the roster is active.
    - createdAt: Time of creation.
    - updatedAt: Time of last update.
    """

    date = models.DateField(blank=False, null=False, help_text="Date")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        """Returns a string representation of the roster."""
        return self.date.strftime("%B %Y")  # Ex: October 2024

    class Meta:
        ordering = ["date"]


class StaffRosterAssignment(models.Model):
    """Represents the information of a staff for a roster.
    Attributes:
    - staff: A staff id.
    - roster: A roster id.
    active: Represents whether a staff is on roster (True) or not (False)
    - vacationDate: The date the staff will go on vacation.
    - resumptionDate: The date the staff will resume work.
    - group: Represents a group number.
    - createdAt: Time of creation.
    - updatedAt: Time of last update.
    """
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name="rosterAssignments")
    roster = models.ForeignKey(Roster, on_delete=models.CASCADE, related_name="staffAssignments")
    active = models.BooleanField(default=True, help_text="Active")
    vacationDate = models.DateField(blank=True, null=True, help_text="Resumption date")
    resumptionDate = models.DateField(blank=True, null=True, help_text="Resumption date")
    group = models.IntegerField(validators=[MinValueValidator])
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def clean(self):
        """Model level validation for vacation and resumption dates."""
        # A staff cannot resume and go on vacation in the same month
        # Hence only one can exist.
        if self.resumptionDate and self.vacationDate:
            raise ValidationError("Only one of resumptionDate and vacationDate can be set.")
        super().clean()

    def isActive(self, date):
        """Checks if a staff is active on a given day."""
        if not self.active:
            return False
        elif self.vacationDate and self.vacationDate <= date:
            return False
        elif self.resumptionDate and self.resumptionDate > date:
            return False
        else:
            return True


class Day(models.Model):
    """Represents a day in a roster.
    Attributes:
    - date: The date of the current day
    - createdAt: Time of creation.
    - updatedAt: Time of last update.
    """
    date = models.DateField(null=False, blank=False)
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        """Returns a string representation of the day."""
        return self.date.strftime("%A %B %d %Y")  # EX: Sunday October 27 2024


class Shift(models.Model):
    """Represents a type of a shift in a day of a roster.
    Attributes:
    - MORNINGSHIFT: A string for `Morning`
    - AFTERNOONSHIFT: A string for `Afternoon`
    - SHIFTTYPES: A dictionary that maps a shift type to a human readable text.
    - shiftType: A choice between morning or afternoon shift.
    - day: A foreign key to `Day` model.
    - staffs: a many to many field to `Staff` model; represents the staffs on shift.
    - createdAt: Time of creation.
    - updatedAt: Time of last update.
    """
    MORNINGSHIFT = "ms"
    AFTERNOONSHIFT = "as"
    SHIFTTYPES: dict[str, str] = {
            MORNINGSHIFT: "Morning shift",
            AFTERNOONSHIFT: "Afternoon shift"
            }
    shiftType = models.CharField(max_length=32, choices=SHIFTTYPES, blank=False, null=False, help_text="Shift type")
    day = models.ForeignKey(Day, on_delete=models.CASCADE, related_name="shifts")
    staffs = models.ManyToManyField(Staff, related_name="shifts")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        """Returns a string representation of a shift."""
        # The simplest approach is to return just the shift type.
        return self.SHIFTTYPES[self.shiftType]

    def isMorningShift(self) -> bool:
        """Checks if the shift is a morning shift."""
        return True if self.shiftType == self.MORNINGSHIFT else False

src/highland_fm_roster/roster/forms.py
"""Forms for the roster app"""
from django.forms import ModelForm

from .models import Staff


class StaffForm(ModelForm):
    """Form for creating and editing staffs."""
    class Meta:
        model = Staff
        fields = ['firstName', 'middleName', 'lastName']

src/highland_fm_roster/roster/views.py
from django.http import HttpRequest as HttpRequestBase
from django.http import HttpResponse, QueryDict
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views import View
from django.views.generic import ListView
from django_htmx.middleware import HtmxDetails

from .forms import StaffForm
from .models import Staff


class HttpRequest(HttpRequestBase):
    htmx: HtmxDetails


class StaffListView(ListView):
    model = Staff
    context_object_name = "staffs"
    template_name = "roster/staff_list.html"


class CreateStaffView(View):
    """A view for creating staffs."""

    def get(self, request):
        """Get method for newStaff page."""
        form = StaffForm()
        return render(request, "roster/new_staff.html", {"form": form})

    def post(self, request):
        """Post method for new staff page."""
        form = StaffForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("roster:staffsList"))


class StaffActionsView(View):
    """View for staff actions like editing and deleting."""

    def get(self, request, id):
        """Returns a form for editing a Staff."""
        staff = get_object_or_404(Staff, pk=id)
        form = StaffForm(
            initial=dict(
                firstName=staff.firstName,
                middleName=staff.middleName,
                lastName=staff.lastName,
            )
        )
        return render(
            request, "roster/staff_edit_modal.html", {"form": form, "staff": staff}
        )

    def put(self, request, id):
        """Edits a staff."""
        staff = get_object_or_404(Staff, pk=id)
        form = StaffForm(QueryDict(request.body.decode()), instance=staff)
        if not form.is_valid():
            return render(
                request,
                "roster/staff_edit_modal.html",
                {
                    "form": form,
                    "staff": staff,
                },
            )
        form.save()
        response = render(
            request,
            "roster/staff_list_item.html",
            {
                "staff": staff,
            },
        )
        response['HX-Retarget'] = f"#staff-{staff.id}"
        response['HX-Reswap'] = "outerHTML"
        return response

    def delete(self, request, id):
        """Deletes a staff."""
        staff = get_object_or_404(Staff, id=id)
        staff.delete()
        response = HttpResponse()
        response['hx-retarget'] = f"#staff-{id}"
        response['hx-reswap'] = 'delete'
        return response

src/highland_fm_roster/roster/templates/roster/footer.html
<footer class="page-footer">
	<div class="footer-copyright">
		<div class="container">
			<p>&copy; 2024 Abdulqadir Ahmad</p>
		</div>
	</div>
</footer>

src/highland_fm_roster/roster/templates/roster/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


<link rel="icon" href="/favicon.ico" sizes="any">

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
<!-- Material Symbols - Outlined Set -->
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
<!-- Compiled and minified CSS -->
<link rel="stylesheet"
	href="https://cdn.jsdelivr.net/npm/@materializecss/materialize@2.1.1/dist/css/materialize.min.css">
<!-- htmx -->
<script src="https://unpkg.com/htmx.org@2.0.3"
	integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq"
	crossorigin="anonymous"></script>
<script>
	const theme = localStorage.getItem("theme");
	if (theme) document.documentElement.setAttribute("theme", theme);
</script>
<script src="{% static 'roster/app.js' %}" defer></script>

src/highland_fm_roster/roster/templates/roster/header.html
<header>
	<h1 class="center">Highland FM Roster</h1>
</header>

src/highland_fm_roster/roster/templates/roster/home.html
{% extends baseTemplate %}
{% block title %}
<title>Home | Highland FM Roster</title>
{% endblock %}

{% block content %}
<h1>Highland FM Roster</h1>
{% endblock %}

src/highland_fm_roster/roster/templates/roster/new_staff.html
{% extends baseTemplate %}

{% block title %}
<title>New Staff | Highland FM Roster</title>
{% endblock %}

{% block content %}
<h1>New Staff</h1>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Create">
</form>
{% endblock %}

src/highland_fm_roster/roster/templates/roster/staff_edit_modal.html
<div id="modal-staff-{{ staff.id }}-edit" class="modal">
	<div class="modal-content">
		<h4>Edit Staff</h4>
		<form
				id="staff-{{ staff.id }}-edit-form"
				hx-put="{% url 'roster:staffActions' staff.id %}"
				>
				{{ csrf_toekn }}
				{{ form.as_p }}
		</form>
	</div>
	<div class="modal-footer">
		<button
				form="staff-{{ staff.id }}-edit-form"
				type="submit"
				class="green-text modal-close waves-effect filled"
				aria-label="Done">
			<i class="material-symbols-outlined">done</i>
		</button>
	</div>
</div>

src/highland_fm_roster/roster/templates/roster/staff_list.html
{% extends baseTemplate %}

{% block title %}
<title>Staffs List | Highland FM Roster</title>
{% endblock %}

{% block content %}
<h1>Staffs List</h1>

<a href="{% url 'roster:newStaff' %}">Add New Staff</a>

<div class="section">
	<ul>
		{% for staff in staffs %}
		{% include 'roster/staff_list_item.html' with staff=staff %}
		{% endfor %}
	</ul>
</div>
{% endblock %}

src/highland_fm_roster/roster/templates/roster/staff_list_item.html
<li
		id="staff-{{ staff.id }}"
		hx-on::after-swap="M.Dropdown.init(this.querySelectorAll('.dropdown-trigger'));console.log(this)"
		>
		{{ staff }}
		<button
				type="button"
				class="outlined waves-effect waves-dark dropdown-trigger"
				data-target="dropdown-staff-{{ staff.id }}"
				aria-label="More options"
				>
				<i class="material-symbols-outlined">more_vert</i>
		</button>
</li>
<ul id="dropdown-staff-{{ staff.id }}" class="dropdown-content">
	<li><a hx-get="{% url 'roster:staffActions' staff.id %}" hx-swap="beforeend" hx-target="#modal-container">Edit</a></li>
	<li><a class="red-text waves-effect" hx-delete="{% url 'roster:staffActions' staff.id %}" hx-confirm="Are you sure you wish to delete {{ staff }}?">Delete</a></li>
</ul>